/*****************************************************************************
 * File generated by HDevelop Version 18.11
 *
 * Do not modify!
 *****************************************************************************/

#ifndef MEASURE_H
#define MEASURE_H

#ifndef __APPLE__
  #include <halconcpp/HalconCpp.h>
#else
  #include <HALCONCpp/HalconCpp.h>
#endif

namespace measure {

/*****************************************************************************
 * SetResourcePath
 *****************************************************************************
 * Use SetResourcePath in your application to specify the location of the 
 * HDevelop script or procedure library.
 *****************************************************************************/
  void SetResourcePath(const char* resource_path);
#ifdef _WIN32
  void SetResourcePath(const wchar_t* resource_path);
#endif

  void get_model(
    HalconCpp::HObject const& ModelImage,
    HalconCpp::HTuple const& RowStart,
    HalconCpp::HTuple const& RowEnd,
    HalconCpp::HTuple* result);


  void ScrewMeasure2D(
    HalconCpp::HObject const& ModelImage,
    HalconCpp::HObject const& Image,
    HalconCpp::HObject* ImageReducedOutput1,
    HalconCpp::HObject* ImageReducedOutput2,
    HalconCpp::HObject* contoursXLDS,
    HalconCpp::HTuple const& ModeRectangleRow1,
    HalconCpp::HTuple const& ModeRectangleRow2,
    HalconCpp::HTuple const& ModeRectangleRow11,
    HalconCpp::HTuple const& ModeRectangleRow22,
    HalconCpp::HTuple const& modelPath,
    HalconCpp::HTuple* toothHeight,
    HalconCpp::HTuple* toothWidth,
    HalconCpp::HTuple* screwWidth,
    HalconCpp::HTuple* screwAngle,
    HalconCpp::HTuple* result,
    HalconCpp::HTuple* message);


  void softtri(
    HalconCpp::HTuple const& AcqHandle);


    
};

#endif